language: python
python:
  - 3.4
env:
  matrix:
    - CI_TARGET=vim
    - CI_TARGET=neovim VROOM_ARGS=--neovim
before_install:
  - if [ $CI_TARGET = neovim ]; then
      pip install neovim;
    fi
install:
  - python setup.py -q install
before_script:
  - if [ $CI_TARGET = vim ]; then
      sudo apt-get install vim-gnome;
    else
      eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64";
    fi
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - vroom $VROOM_ARGS --crawl ./examples/
