language: python
install:
  - python setup.py -q install
before_script:
  - sudo apt-get install vim-gnome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - vroom --crawl ./examples/
